/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telaprin;
import javax.swing.*;
import java.awt.Toolkit;



public class TelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        initComponents();
        InserirIcone(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LtituloPrin = new javax.swing.JLabel();
        painelPrin = new javax.swing.JPanel();
        bEditaImg = new javax.swing.JButton();
        bAdicionarImg = new javax.swing.JButton();
        bPesquisaImg = new javax.swing.JButton();
        LtxtOpcoes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SavePicture");
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(102, 102, 102));
        setLocation(new java.awt.Point(400, 85));
        setName("TelaMenu"); // NOI18N
        setResizable(false);

        LtituloPrin.setBackground(new java.awt.Color(102, 102, 102));
        LtituloPrin.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        LtituloPrin.setForeground(new java.awt.Color(255, 255, 255));
        LtituloPrin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LtituloPrin.setText("SavePicture");
        LtituloPrin.setOpaque(true);

        painelPrin.setBackground(new java.awt.Color(153, 153, 153));

        bEditaImg.setBackground(new java.awt.Color(51, 51, 51));
        bEditaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgProjeto/imgTelaPrin/editar.png"))); // NOI18N
        bEditaImg.setToolTipText("Edite suas imagens armazenadas no banco de dados e exclua-as quando desejar.\n"); // NOI18N
        bEditaImg.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar Imagem", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Segoe UI Emoji", 2, 14), new java.awt.Color(204, 204, 204))); // NOI18N
        bEditaImg.setDefaultCapable(false);
        bEditaImg.setFocusPainted(false);
        bEditaImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditaImgActionPerformed(evt);
            }
        });

        bAdicionarImg.setBackground(new java.awt.Color(51, 51, 51));
        bAdicionarImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgProjeto/imgTelaPrin/adicionar-imagem1.png"))); // NOI18N
        bAdicionarImg.setToolTipText("Adicione e salve as suas imagens diretamente no banco de dados. Os arquivos suportados são: .jpg, .png, .bmp");
        bAdicionarImg.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicionar Imagem", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Segoe UI Historic", 2, 14), new java.awt.Color(204, 204, 204))); // NOI18N
        bAdicionarImg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bAdicionarImg.setFocusPainted(false);
        bAdicionarImg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bAdicionarImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdicionarImgActionPerformed(evt);
            }
        });

        bPesquisaImg.setBackground(new java.awt.Color(51, 51, 51));
        bPesquisaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgProjeto/imgTelaPrin/pesquisa-de-imagens.png"))); // NOI18N
        bPesquisaImg.setToolTipText("Consulte suas imagens utilizando diferentes métodos de ordenação, cada um com seu próprio ritmo de processamento.");
        bPesquisaImg.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ordenar Imagem", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Segoe UI Emoji", 2, 14), new java.awt.Color(204, 204, 204))); // NOI18N
        bPesquisaImg.setFocusPainted(false);
        bPesquisaImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPesquisaImgActionPerformed(evt);
            }
        });

        LtxtOpcoes.setFont(new java.awt.Font("Yu Gothic", 2, 14)); // NOI18N
        LtxtOpcoes.setForeground(new java.awt.Color(204, 204, 204));
        LtxtOpcoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LtxtOpcoes.setText("Escolha uma das opções.");

        javax.swing.GroupLayout painelPrinLayout = new javax.swing.GroupLayout(painelPrin);
        painelPrin.setLayout(painelPrinLayout);
        painelPrinLayout.setHorizontalGroup(
            painelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrinLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(painelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bPesquisaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAdicionarImg, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEditaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(painelPrinLayout.createSequentialGroup()
                .addComponent(LtxtOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        painelPrinLayout.setVerticalGroup(
            painelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LtxtOpcoes)
                .addGap(18, 18, 18)
                .addComponent(bAdicionarImg, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bPesquisaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bEditaImg, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(painelPrin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(LtituloPrin, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LtituloPrin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(painelPrin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bPesquisaImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPesquisaImgActionPerformed
        TelaOrdenar telaOrdem = new TelaOrdenar();
        telaOrdem.setVisible(true);
        dispose();
    }//GEN-LAST:event_bPesquisaImgActionPerformed

    private void bAdicionarImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdicionarImgActionPerformed
        TelaAdicionar telaAdd = new TelaAdicionar();
        telaAdd.setVisible(true);
        dispose();
    }//GEN-LAST:event_bAdicionarImgActionPerformed

    private void bEditaImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditaImgActionPerformed
        TelaEditar telaEdit = new TelaEditar();
        telaEdit.setVisible(true);
        dispose();
    }//GEN-LAST:event_bEditaImgActionPerformed
    public void InserirIcone (JFrame frm){
        try{
            frm.setIconImage(Toolkit.getDefaultToolkit().getImage("src/imgProjeto/imgTelaPrin/iconetelaprin.png"));
        }catch(Exception ex){
            System.out.println(ex.toString());         
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LtituloPrin;
    private javax.swing.JLabel LtxtOpcoes;
    private javax.swing.JButton bAdicionarImg;
    private javax.swing.JButton bEditaImg;
    private javax.swing.JButton bPesquisaImg;
    private javax.swing.JPanel painelPrin;
    // End of variables declaration//GEN-END:variables
}
